### PR TITLE
Update plan.yml

### PR DESCRIPTION
**Pull request by Spartakovic**

### CODE REVIEW

**Comment by Spartakovic** [comment]
digger plan

**Comment by Spartakovic** [comment]
digger unlock

**Comment by Spartakovic** [comment]
digger lock

**Comment by Spartakovic** [comment]
digger lock

**Comment by Spartakovic** [comment]
digger unlock

**Comment by Spartakovic** [comment]
digger unlock

**Comment by Spartakovic** [comment]
digger lock

**Comment by motatoes** [comment]
digger unlock

**Pull request closed without merging**
